python3 ../test_four_option_eval/test_unified.py \
  --model_name llama3.2-vision:latest \
  --api_key ollama \
  --base_url http://localhost:11434/v1 \
  --data_root /home/student0/Physical_Intuition_test/balanced_dataset \
  --output_dir /home/student0/Physical_Intuition_test/test_results/four_option/llama3.2-vision:latest \
  --num_sets 10 \
  --repetitions 4 \
  --max_tokens 512 \
  --temperature 0.7 \
  --top_p 0.9 \
  --game_type Basic